name: Daemon Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd daemon
          cp setup.py.in setup.py
          cp core/constants.py.in core/constants.py
          sed -i 's/True/False/g' core/constants.py
          pipenv sync --dev
      - name: isort
        run: |
          cd daemon
          pipenv run isort -c -df
      - name: black
        run: |
          cd daemon
          pipenv run black --check --exclude ".+_pb2.*.py|doc|build|utm\.py|setup\.py" .
      - name: flake8
        run: |
          cd daemon
          pipenv run flake8
      - name: grpc
        run: |
          cd daemon/proto
          pipenv run python -m grpc_tools.protoc -I . --python_out=.. --grpc_python_out=.. core/api/grpc/*.proto
      - name: test
        run: |
          cd daemon
          pipenv run test --mock
